pipeline {  
  agent {  
    docker {  
      image 'node:14-alpine' // 使用更新的Node.js版本  
    }  
  }  
  stages {  
    stage('Build') {  
      steps {  
        sh 'npm install'  
      }  
    }  
    stage('Test') {  
      environment {  
        CI = 'true'  
      }  
      steps {  
        sh './jenkins/scripts/test.sh'  
      }  
    }  
  }  
}
